### PR TITLE
EBS Pricing Support

### PR DESCRIPTION
**Pull request by vecchp**
I've started working on including the EBS optimization surcharge when selecting instance types.  I believe this is all that needs to be done to grab the price data from the json.

### CODE REVIEW

**Comment by cristim** [comment]
I think the instance data source file also needs to be regenerated after this change.

**Comment by vecchp** [comment]
Is that true?  When I grabbed the binary json from master and decoded it it had the ebs field.

**Comment by cristim** [comment]
The json is just a data source file, it needs to be processed using a make target which basically embeds it as a string into a golang source, which is the most of this library code.

When the go code is compiled it can parse the json string it into that data structure you edited, which not necessarily replicates the content of the json.

Even if the json contained the EBS data, I  would still recommend to update it,in order to get the latest pricing information, since AWS updates it all the time.

**Review by cristim — APPROVED** [review]

**Comment by cristim** [comment]
@vecchp please let me know when you are ready to merge this PR

**Comment by vecchp** [comment]
@cristim all good to merge

**Pull request merged**
